before_deploy:
  - mkdir build
  - cp LICENSE build
  - cp README.txt build
  - cp remove-medium-cross-links.php build
 
deploy:
  - provider: wordpress-plugin
    edge:
      source: TypistTech/dpl
      branch: add-wordpress-plugin-deployment
    on:
      php: 7.1
      tags: true
      repo: bitpay/bitpay-checkout-for-woocommerce
    slug: bitpay-checkout-for-woocommerce
    username: sales-engineering@bitpay.com
    password: $WORDPRESS_ORG_PASSWORD
    build_dir: build 
